

// Generated by com.google.auto.value.processor.AutoValueProcessor
 final class AutoValue_Item10_2_Parent extends Item10_2.Parent {

  private final int intOne;

  AutoValue_Item10_2_Parent(
      int intOne) {
    this.intOne = intOne;
  }

  @Override
  int intOne() {
    return intOne;
  }

  @Override
  public String toString() {
    return "Parent{"
        + "intOne=" + intOne
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Item10_2.Parent) {
      Item10_2.Parent that = (Item10_2.Parent) o;
      return (this.intOne == that.intOne());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h = 1;
    h *= 1000003;
    h ^= this.intOne;
    return h;
  }

}
