

// Generated by com.google.auto.value.processor.AutoValueProcessor
 final class AutoValue_Item10_2_Child extends Item10_2.Child {

  private final Item10_2.Parent parent;
  private final int intTwo;

  AutoValue_Item10_2_Child(
      Item10_2.Parent parent,
      int intTwo) {
    if (parent == null) {
      throw new NullPointerException("Null parent");
    }
    this.parent = parent;
    this.intTwo = intTwo;
  }

  @Override
  Item10_2.Parent parent() {
    return parent;
  }

  @Override
  int intTwo() {
    return intTwo;
  }

  @Override
  public String toString() {
    return "Child{"
        + "parent=" + parent + ", "
        + "intTwo=" + intTwo
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Item10_2.Child) {
      Item10_2.Child that = (Item10_2.Child) o;
      return (this.parent.equals(that.parent()))
           && (this.intTwo == that.intTwo());
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h = 1;
    h *= 1000003;
    h ^= this.parent.hashCode();
    h *= 1000003;
    h ^= this.intTwo;
    return h;
  }

}
